spring.profiles.active: local
spring:
  application:
    name: Kotlin Exercise

server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: local

  devtools:
    livereload:
      enabled: true
    remote:
      restart:
        enabled: true

  jackson:
    default-property-inclusion: non_null
    deserialization:
      adjust_dates_to_context_time_zone: false

  web:
    resources:
      static-locations: file:src/main/resources/static/
      cache:
        period: 0

  mvc:
    log-request-details: true
    static-path-pattern: /static/**

  thymeleaf:
    enabled: true
    check-template-location: true
    suffix: .html
    cache: false
    prefix: file:src/main/resources/templates/

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://34.64.101.150/board
    username: paul
    password: paul

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

logging:
  level:
    web: debug
    org.hibernate.sql: debug